offence_tracker/urls.py
from django.conf.urls import url
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^report/', views.report, name='report'),
    url(r'^login_u/$', views.login_u, name='login_u'),
    url(r'^logout_u/$', views.logout_u, name='logout_u'),
    url(r'^archive/$', views.archive, name='archive'),
    url(r'^archive/(?P<BLOCK>[A-Z]+)', views.archive_block, name='archive_block'),
    url(r'^archive/all/$', views.archive_all, name='archive_all'),
    url(r'^archive/(?P<day>[0-9]+)/(?P<month>[0-9]+)/(?P<year>[0-9]+)/$', views.archive_date, name='archive_date'),
    url(r'^delete_offence/(?P<id>[0-9]+)/$', views.delete_offence, name='delete_offence'),
    url(r'^register/$', views.register, name='register'),
]

offence_tracker/models.py
from django.db import models

# Create your models here.
OFFENCES = (
    ('RL', 'Late Reporting Time'),
    ('LONW', 'Learning Objective Not Written'),
    ('TNH', 'Teaching Not Happening'),
    ('CCN', 'No Class Control'),
    ('SMO', 'Students Moving Outside'),
    ('NHE', 'No Happiness Exercise'),
)

BLOCKS = (
    ('P', 'Primary'),
    ('M', 'Middle'),
    ('S', 'Senior'),
)

FLOORS = (
    ('G', 'Ground'),
    ('F', 'First'),
    ('S', 'Second'),
)


class Offence(models.Model):
    id = models.AutoField(primary_key=True, editable= False)
    date = models.DateTimeField(auto_now_add=True)
    block = models.CharField(max_length = 1,choices = BLOCKS)
    floor = models.CharField(max_length = 1,choices = FLOORS)
    period = models.CharField(max_length = 1)
    type = models.CharField(max_length = 4,choices = OFFENCES)
    grade = models.CharField(max_length = 2)
    section = models.CharField(max_length = 1)
    reporter = models.CharField(max_length=50, null=True,blank = True)

    def __str__(self):
        return str(self.date) + "-" + self.block + "-" + self.period +"-"+ self.type+"-"+ str(self.reporter)

offence_tracker/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Offence

class OffenceForm(forms.ModelForm):

    class Meta:
        model = Offence
        fields = ['type','block','floor','period','grade','section']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password','first_name','last_name']

offence_tracker/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from .forms import OffenceForm, UserForm
from .models import Offence
from django.contrib.auth.models import User
from django.shortcuts import render, redirect , Http404
import pytz
from django.contrib import messages
import datetime
from datetime import date
# Create your views here.


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'offence_tracker/login.html')
    if request.user.is_staff or request.user.is_superuser:
        return redirect('/archive')
    else:
        return redirect('/report')

def report(request):
    if not request.user.is_authenticated():
        return render(request, 'login.html')
    else:
        form = OffenceForm(request.POST)
        if form.is_valid():
            offence = form.save(commit=False)
            user_id = request.user
            user_obj = User.objects.get(username= user_id)
            offence.reporter = user_obj.first_name + " " + user_obj.last_name
            render(request, 'offence_tracker/archive.html', {'form': form})
            offence.save()
            messages.success(request, 'Success')
    return render(request, 'offence_tracker/report_form.html', {'form' : form})

def login_u(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('/report')
            else:
                return render(request, 'offence_tracker/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'offence_tracker/login.html', {'error_message': 'Invalid login'})
    return render(request, 'offence_tracker/login.html')

def logout_u(request):
    logout(request)
    form = UserForm(request.POST or None)
    return render(request, 'offence_tracker/login.html', {'form' : form})

def archive(request):
    if not request.user.is_authenticated():
        return render(request, 'offence_tracker/login.html')
    if request.user.is_staff or request.user.is_superuser:
        context = {
            'offences': Offence.objects.order_by('date').reverse().filter(date__date = date.today()),
            'isStaff': True,
        }
        return render(request, 'offence_tracker/archive.html', context)
    else:
        user_id = request.user
        user_obj = User.objects.get(username=user_id)
        reporter = user_obj.first_name + " " + user_obj.last_name
        context = {'offences': Offence.objects.filter(reporter = reporter).order_by('date').reverse().filter(date__date = date.today())}
        return render(request, 'offence_tracker/archive.html', context)

def delete_offence(request, id):
        offence = Offence.objects.get(pk=id)
        offence.delete()
        return redirect('/archive')

def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('/')
    context = {
        "form": form,
    }
    return render(request, 'offence_tracker/register.html', context)

def archive_date(request,day,month,year):
    if not request.user.is_authenticated():
        return render(request, 'offence_tracker/login.html')
    if request.user.is_staff or request.user.is_superuser:
        context = {
            'offences': Offence.objects.order_by('date').reverse().filter(date__contains=datetime.date(int(year), int(month), int(day))),
            'isStaff': True,
        }
        return render(request, 'offence_tracker/archive.html', context)
    else:
        user_id = request.user
        user_obj = User.objects.get(username=user_id)
        reporter = user_obj.first_name + " " + user_obj.last_name
        context = {
            'offences': Offence.objects.filter(reporter = reporter).order_by('date').reverse().filter(date__contains=datetime.date(int(year), int(month), int(day)))
        }
        return render(request, 'offence_tracker/archive.html', context)

def archive_all(request):
    if not request.user.is_authenticated():
        return render(request, 'offence_tracker/login.html')
    if request.user.is_staff or request.user.is_superuser:
        context = {
            'offences': Offence.objects.order_by('date').reverse(),
            'isStaff': True,
        }
        return render(request, 'offence_tracker/archive.html', context)
    else:
        user_id = request.user
        user_obj = User.objects.get(username=user_id)
        reporter = user_obj.first_name + " " + user_obj.last_name
        context = {
            'offences': Offence.objects.filter(reporter = reporter).order_by('date').reverse()
        }
        return render(request, 'offence_tracker/archive.html', context)

def archive_block(request,BLOCK):
    if not request.user.is_authenticated():
        return render(request, 'offence_tracker/login.html')
    if request.user.is_staff or request.user.is_superuser:
        context = {
            'offences': Offence.objects.order_by('date').reverse().filter(block=BLOCK),
            'isStaff': True,
        }
        return render(request, 'offence_tracker/archive.html', context)
    else:
        user_id = request.user
        user_obj = User.objects.get(username=user_id)
        reporter = user_obj.first_name + " " + user_obj.last_name
        context = {
            'offences': Offence.objects.filter(reporter = reporter).order_by('date').reverse()
        }
        return render(request, 'offence_tracker/archive.html', context)

offence_tracker/templates/offence_tracker/archive.html
{% extends 'offence_tracker/base.html' %}
{% block title %}Archive{% endblock %}
{% block body %}
<nav aria-label="...">
  <ul class="pager">
    <li><a href = {% url 'offence_tracker:archive_all' %}> View All</a> </li>
<li><a href = "http://copdpsd.info.tm/archive/P/"> Primary</a> </li>
<li><a href = "http://copdpsd.info.tm/archive/M/"> Middle</a> </li>
<li><a href = "http://copdpsd.info.tm/archive/S/"> Senior</a> </li>
  </ul>
</nav>
<div class = "container-fluid">
<div class="list-group" >
    {% for offence in offences %}
         <div class="list-group-item">
            <h2 class="list-group-item-heading">{{ offence.get_type_display }}</h2>
            <p class="list-group-item-text">
                <b>Date / Time:</b> {{ offence.date }} </br>
                <b>Block:</b> {{ offence.get_block_display }}</br>
                <b>Floor:</b> {{ offence.get_floor_display }}</br>
                <b>Class :</b> {{ offence.grade }} - {{ offence.section }}</br>
                <b>Period:</b> {{ offence.period }}</br>
                <b>Reported by :</b> {{ offence.reporter }}</br>
                <a href = "/delete_offence/{{ offence.id }}"> Remove </a></br>
            </p>
        </div>
    {% endfor %}
</div>
</div>
{% endblock %}

offence_tracker/templates/offence_tracker/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>COP</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'offence_tracker/style.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="glyphicon glyphicon-arrow-down"></span>
            </button>
            <a class="navbar-brand" href="{% url 'offence_tracker:index' %}">COP</a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'offence_tracker:archive' %}"><span class="glyphicon glyphicon-list" aria-hidden="true"></span>&nbsp; Archive</a></li>
                <li>
                    <a href="{% url 'offence_tracker:report' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Submit
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_superuser %}     
<li>
					<a href="{% url 'admin:index' %}">
						<span class="glyphicon glyphicon-dashboard" aria-hidden="true"></span>&nbsp; Admin
					</a>
				</li>    {% endif %}
				<li>
                    <a href="{% url 'offence_tracker:logout_u' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

offence_tracker/templates/offence_tracker/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>COP</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'offence_tracker/style.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="glyphicon glyphicon-arrow-down"></span>
            </button>
            <a class="navbar-brand" href="{% url 'offence_tracker:index' %}">COP</a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'offence_tracker:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'offence_tracker:login_u' %}">Log In</a></li>
            </ul>
        </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

offence_tracker/templates/offence_tracker/login.html
{% extends 'offence_tracker/base_visitor.html' %}
{% block title %}Teacher Trak{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'offence_tracker:login_u'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Forgot Password? <a href="{% url 'password_reset' %}">Click here</a>.
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'offence_tracker:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

offence_tracker/templates/offence_tracker/register.html
{% extends 'offence_tracker/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <span class="text-danger small">{{ field.errors }}</span>
                                </div>
                                <label class="control-label col-sm-2" >{{ field.label_tag }}</label>
                                <div class="col-sm-10">{{ field }}</div>
                            </div>
                        {% endfor %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'offence_tracker:login_u' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

offence_tracker/templates/offence_tracker/report_form.html
{% extends 'offence_tracker/base.html' %}
{% block title %}Report{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h1>Submit</h1>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <span class="text-danger small">{{ field.errors }}</span>
                                </div>
                                <label class="control-label col-sm-2" >{{ field.label_tag }}</label>
                                <div class="col-sm-10">{{ field }}</div>
                            </div>
                        {% endfor %}
                        {% if messages %}
                        <div class="messages">
                            {% for message in messages %}
                            <div class="alert alert-success" role="alert">{{ message }}</div>
                            {% endfor %}
                        </div>
                        {% endif %}
                         <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}